CREATE TABLE IF NOT EXISTS user_result (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    result_id VARCHAR(64) UNIQUE NOT NULL,
    birth_year INT NOT NULL,
    birth_month INT NOT NULL,
    birth_day INT NULL,
    birth_time_range VARCHAR(32) NULL,
    answer_json TEXT NOT NULL,
    primary_element VARCHAR(32) NOT NULL,
    secondary_element VARCHAR(32) NOT NULL,
    primary_percent INT NOT NULL,
    secondary_percent INT NOT NULL,
    all_element_scores_json TEXT NOT NULL,
    persona_type_id VARCHAR(96) NULL,
    accent_element VARCHAR(32) NULL,
    relation_kind VARCHAR(32) NULL,
    persona_label VARCHAR(96) NULL,
    day_master_text TEXT NULL,
    primary_secondary_text TEXT NULL,
    accent_text TEXT NULL,
    heaven_text TEXT NULL,
    human_text TEXT NULL,
    star_officer_text TEXT NULL,
    growth_advice_json TEXT NULL,
    star_officer_code VARCHAR(64) NOT NULL,
    star_officer_name VARCHAR(64) NOT NULL,
    keywords_json TEXT NOT NULL,
    layout_explanation TEXT NOT NULL,
    strength_text TEXT NOT NULL,
    relationship_text TEXT NOT NULL,
    card_image_key VARCHAR(128) NULL,
    status TINYINT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uk_result_id(result_id),
    INDEX idx_created_at(created_at),
    INDEX idx_primary_secondary(primary_element, secondary_element),
    INDEX idx_persona_type_id(persona_type_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS short_link (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    short_code VARCHAR(32) UNIQUE NOT NULL,
    result_id VARCHAR(64) NOT NULL,
    original_path VARCHAR(255) NOT NULL,
    short_url VARCHAR(255) NOT NULL,
    pv_count BIGINT NOT NULL DEFAULT 0,
    uv_count BIGINT NOT NULL DEFAULT 0,
    uip_count BIGINT NOT NULL DEFAULT 0,
    last_visit_at DATETIME NULL,
    status TINYINT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uk_short_code(short_code),
    INDEX idx_result_id(result_id),
    INDEX idx_created_at(created_at),
    INDEX idx_status_created_at(status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS visit_event (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    event_type VARCHAR(64) NOT NULL,
    page_path VARCHAR(255) NULL,
    result_id VARCHAR(64) NULL,
    short_code VARCHAR(32) NULL,
    client_id_hash VARCHAR(128) NULL,
    session_id_hash VARCHAR(128) NULL,
    ip_hash VARCHAR(128) NULL,
    user_agent_hash VARCHAR(128) NULL,
    channel VARCHAR(64) NULL,
    campaign VARCHAR(64) NULL,
    device_type VARCHAR(32) NULL,
    referer VARCHAR(512) NULL,
    event_date DATE NULL,
    created_at DATETIME NOT NULL,
    INDEX idx_event_type_created(event_type, created_at),
    INDEX idx_short_code_created(short_code, created_at),
    INDEX idx_result_id_created(result_id, created_at),
    INDEX idx_created_at(created_at),
    INDEX idx_created_client(created_at, client_id_hash),
    INDEX idx_created_ip(created_at, ip_hash),
    INDEX idx_event_created_short(event_type, created_at, short_code),
    INDEX idx_client_id(client_id_hash),
    INDEX idx_ip_hash(ip_hash),
    INDEX idx_session_id(session_id_hash),
    INDEX idx_channel_created(channel, created_at),
    INDEX idx_campaign_created(campaign, created_at),
    INDEX idx_result_event_channel(result_id, event_type, channel),
    INDEX idx_event_short_created_channel(event_type, short_code, created_at, channel),
    INDEX idx_event_date(event_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS site_daily_metric (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    metric_date DATE NOT NULL,
    pv BIGINT NOT NULL DEFAULT 0,
    uv BIGINT NOT NULL DEFAULT 0,
    uip BIGINT NOT NULL DEFAULT 0,
    home_views BIGINT NOT NULL DEFAULT 0,
    start_clicks BIGINT NOT NULL DEFAULT 0,
    test_submits BIGINT NOT NULL DEFAULT 0,
    result_created BIGINT NOT NULL DEFAULT 0,
    short_link_created BIGINT NOT NULL DEFAULT 0,
    short_link_visits BIGINT NOT NULL DEFAULT 0,
    aggregated_at DATETIME NOT NULL,
    UNIQUE KEY uk_site_daily_metric_date(metric_date),
    INDEX idx_site_daily_metric_aggregated_at(aggregated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS short_link_daily_metric (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    metric_date DATE NOT NULL,
    short_code VARCHAR(32) NOT NULL,
    pv BIGINT NOT NULL DEFAULT 0,
    uv BIGINT NOT NULL DEFAULT 0,
    uip BIGINT NOT NULL DEFAULT 0,
    last_visit_at DATETIME NULL,
    aggregated_at DATETIME NOT NULL,
    UNIQUE KEY uk_short_link_daily_metric(metric_date, short_code),
    INDEX idx_short_link_daily_metric_code(short_code, metric_date),
    INDEX idx_short_link_daily_metric_pv(metric_date, pv)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS analytics_visitor (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    visitor_id_hash VARCHAR(128) NOT NULL,
    first_seen_at DATETIME NOT NULL,
    last_seen_at DATETIME NOT NULL,
    user_agent_hash VARCHAR(128) NULL,
    ip_hash VARCHAR(128) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uk_analytics_visitor_id(visitor_id_hash),
    INDEX idx_analytics_visitor_last_seen(last_seen_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS analytics_session (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    session_id_hash VARCHAR(128) NOT NULL,
    visitor_id_hash VARCHAR(128) NOT NULL,
    started_at DATETIME NOT NULL,
    last_heartbeat_at DATETIME NOT NULL,
    ended_at DATETIME NULL,
    entry_path VARCHAR(255) NULL,
    latest_path VARCHAR(255) NULL,
    referrer VARCHAR(512) NULL,
    device_type VARCHAR(32) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uk_analytics_session_id(session_id_hash),
    INDEX idx_analytics_session_visitor(visitor_id_hash),
    INDEX idx_analytics_session_last_heartbeat(last_heartbeat_at),
    INDEX idx_analytics_session_online(last_heartbeat_at, ended_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS analytics_metric_snapshot (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    metric_time DATETIME NOT NULL,
    online_visitors BIGINT NOT NULL DEFAULT 0,
    online_sessions BIGINT NOT NULL DEFAULT 0,
    pv_1m BIGINT NOT NULL DEFAULT 0,
    uv_1m BIGINT NOT NULL DEFAULT 0,
    result_generated_1m BIGINT NOT NULL DEFAULT 0,
    share_click_1m BIGINT NOT NULL DEFAULT 0,
    match_enter_1m BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    UNIQUE KEY uk_analytics_metric_time(metric_time),
    INDEX idx_analytics_metric_time(metric_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
